#+title: Forms of Business Organization
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup


* Sole Proprietorship
  

Benefits:
+ Since there is no distinction between the owner and the manager, income is only taxed once.
+ There is no agency problem (as there is no *agent*).
  
Costs:
+ Unlimited liability to the owner/manager.
+ Life of sole proprietorship is equivalent to the life of the owner.
+ Financing is limited to what the owner can invest and borrow.  Can't sell equity.
+ Transferring ownership means dissolving the proprietorship.


* Partnership

The benefits and costs of a partnership are the same as a sole proprietorship, except that there are many owners instead of one (which may cause a limited agency problem).  In practice there can be partners with limited liability, however we won't cover these other details of partnerships in this course. 

* Corporation
  
A corporation is a separate legal entity from the owner(s) (stockholders).  This shields the owners of the corporation from having to pay business debts---debts of the corporation are *not* debts of the owners.  We say that stockholders have *limited liability*. 

Benefits:
+ Limited liability to the owners.
+ There is no agency problem (as there is no *agent*).
  
Costs:
+ Since the owner and the manager are separate legal entities, income is taxed twice by the time it reaches the owner.
+ Life of sole proprietorship is equivalent to the life of the owner.
  
Most businesses, as they grow, will become a corporation.

#+BEGIN_EXAMPLE
You may hear some lamenting the double taxation of corporations.  On the news they will usually feign a little surprise, but is double taxation surprising?   

A sole proprietorship is taxed once, but since the owner is the same legal entity as the business, the owner is also liable for business debts.  So the owner creates a *new* legal entity which is the business itself, and the owner is now not liable for the businesses debts. But since his is a separate legel entity, it has to pay taxes also.  

So double taxation wasn't created to hinder business, it is a consequence of obtaining limited liability for the owner. The owner can have single taxation whenever they want, they just have to assume the businesses debts. 
#+END_EXAMPLE

* Balance

So when a firm is deciding whether to take the corporate form, it weighs the benefits of the corporate form versus the costs.
