#+title: Forms of Business Organization
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup


* Sole Proprietorship
  

Benefits:
+ Since there is no distinction between the owner and the manager, income is only taxed once.
+ There is no agency problem (as there is no *agent*).
  
Costs:
+ Unlimited liability to the owner/manager.
+ Life of sole proprietorship is equivalent to the life of the owner.
+ Financing is limited to what the owner can invest and borrow.  Can't sell equity.
+ Transferring ownership means dissolving the proprietorship.


* Partnership

The benefits and costs of a partnership are the same as a sole proprietorship, except that there are many owners instead of one (which may cause a limited agency problem).  In practice there can be partners with limited liability, however we won't cover these other details of partnerships in this course. 

* Corporation
  
A corporation is a separate legal entity from the owner(s) (stockholders).  This shields the owners of the corporation from having to pay business debts---debts of the corporation are *not* debts of the owners.  We say that stockholders have *limited liability*. 

Benefits:
+ Limited liability to the owners.
+ Infinitely lived.

Costs:
+ Since the owner and the manager are separate legal entities, income is taxed twice by the time it reaches the owner.
+ Ownership and management have been separated, and hence there is a substantial agency problem (cost).


Most businesses, as they grow, will become a corporation.

#+BEGIN_QUOTE
You may hear some lamenting the double taxation of corporations.  On the news they will usually feign a little surprise, but is double taxation surprising?   

A sole proprietorship is taxed once, but since the owner is the same legal entity as the business, the owner is also liable for business debts.  So the owner creates a *new* legal entity which is the business itself, and the owner is now not liable for the businesses debts. But since his is a separate legel entity, it has to pay taxes also.  

So double taxation wasn't created to hinder business, it is a consequence of obtaining limited liability for the owner. The owner can have single taxation whenever they want, they just have to assume the businesses debts. 
#+END_QUOTE

** Foreign Corporations

Legal systems and laws differ among countries, and so does the definition of a corporation.  Remember a corporation is a /legal entity/ and this is specific to a jurisdiction.  The differing definition of a corporation between countries will be important in the next section where we define the /Goal of Financial Management/.

* Balance

So when a firm is deciding whether to take the corporate form, it weighs the benefits of the corporate form versus the costs.

* Corporations and Financial Markets

That the corporation is infinitely-lived facilitates selling equity (known as stock) and debt (notes and bonds) to finance the company's assets.  Securities (stock and bonds) are sold in /financial markets/.

** Primary Markets vs Secondary Markets

Primary market transactions are those that involve the company, such as initial public offerings (IPO) or seasoned equity offerings (SEO).  In secondary markets, investors exchange securities among themselves, and the corporation itself is not part of the trade.  That does not mean the managers and owners of corporation are not interested however---management compensation is commonly determined by secondary market security (mainly stock) prices.

We make a distinction between primary and secondary markets because their structure and participants are quite different.  Think of pricing an IPO where you don't have a publicly traded stock price to reference.  This can be quite difficult, and is often accomplished via /bookbuilding/.  This is where you go to various investors and ask what they would pay. Alternatively, you are valuing a stock in the secondary market, you already have a market clearing price available.

We will talk about stock and bond secondary market structure in later chapters, however here note that they are actively evolving.  Trading venues and mechanisms are vastly different today than they were 40 years ago, and they will likely be very different in 40 years.


